# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ddOZG7w7MQdg62Ewo2TviZX4cN42FToO

# matplotlib
"""

pip install matplotlib

import matplotlib as mlt
import numpy as np

list = [1,2,2,3,4,5,5,123,123,12321,31,312,312]
print(list.index(1))
print(list)
tuple = ('apple','bannana ','watermellon','mango')
print(tuple[1])
print(tuple[-2])

"""**Numpy**"""



"""**Lit**

**tuple**

**set**
"""



my_list = (1,2,2,3,4,5,5,123,123,12321,31,312,312)
new = list(my_list)
print(new)

my_set = {1,2,3,4,5,7,8,1,3}
mySet_2 = {1,2,123,1234,123124}

union = my_set.union(mySet_2)
intersection = my_set.intersection(mySet_2)
difference = my_set.difference(mySet_2)

print(union)
print(intersection)
print(difference)

my_set.add(11232)
print(my_set)

my_set.remove(1)
print(my_set)

student = {
    "name" : "hasnain",
    "gpa" : 4.0,
    "semester" : 6,
    "age" : 21,
    "is_student" : True

    }

print(student["name"])

student["name"] = "ali"

print(student["name"])

student2 = {
    "name" : "hasnain",
    "gpa" : 4.0,
    "semester" : 6,
    "age" : 21,
    "is_student" : True,
    "name" : "ali"

    }

print(student2["name"])

